name: lintinig, testing, building
on:
  push:
     branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install modules (yarn)
        run: yarn install -g

      - name: Build production version
        run: yarn run build-prod

      - name: Lint TS
        run: yarn run lint-ts

      - name: Lint SCSS
        run: yarn run lint-scss

      - name: Unit testing
        run: yarn run test-unit

      - name: Run Storybook
        run: yarn run build-storybook

      - name: Run Loki testing
        run: yarn run test-ui-ci

