name: lintinig, testing, building
on:
  push:
     branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: yarn install
      - name: build production version
        run: yarn run build:prod
      - name: lint ts
        run: yarn run lint:ts
      - name: lint scsss
        run: yarn run lint:scss
      - name: run storybook
        run: yarn run build-storybook
      - name: run unit testing
        run: yarn run test-unit
